# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47b3c7c825205faa5098971f71f2682f18afce0e5653a086e209d243affdf1c437c82215a6444e6deba665d5b13774be6a51eabda5d687fb0805a482140f1e16

test:
  secret_key_base: 4bb340698452950bf2f3e5f524cd6fd226f259606126985a90707ebfbab7903fe9f3d572b5b3b0d71f2f80b93f23f97d004c07825bf653a5b3328fe0d82095b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
